CREATE TABLE "PLAYERS" (
	"id"	INTEGER,
	"Player"	TEXT,
	"Pos"	TEXT,
	"Age"	REAL,
	"Tm"	TEXT,
	"G"	REAL,
	"GS"	REAL,
	"MP"	REAL,
	"FG"	REAL,
	"FGA"	REAL,
	"FG%"	REAL,
	"3P"	REAL,
	"3PA"	REAL,
	"3P%"	REAL,
	"2P"	REAL,
	"2PA"	REAL,
	"2P%"	REAL,
	"FT"	REAL,
	"FTA"	REAL,
	"FT%"	REAL,
	"ORB"	REAL,
	"DRB"	REAL,
	"TRB"	REAL,
	"AST"	REAL,
	"STL"	REAL,
	"BLK"	REAL,
	"TOV"	REAL,
	"PF"	REAL,
	"PTS"	REAL,
	PRIMARY KEY("id")
);

CREATE TABLE "ROOKIES" (
	"id"	INTEGER,
	"Player"	TEXT,
	"Debut"	TEXT,
	"Age"	REAL,
	"G"	REAL,
	"MP"	REAL,
	"FG"	REAL,
	"FGA"	REAL,
	"3P"	REAL,
	"3PA"	REAL,
	"FT"	REAL,
	"FTA"	REAL,
	"ORB"	REAL,
	"TRB"	REAL,
	"AST"	REAL,
	"STL"	REAL,
	"BLK"	REAL,
	"TOV"	REAL,
	"PF"	REAL,
	"PTS"	REAL,
	"FG%"	REAL,
	"3P%"	REAL,
	"FT%"	REAL,
	PRIMARY KEY("id")
);

CREATE TABLE "TEAMS" (
	"id"	INTEGER,
	"Key"	TEXT,
	"Team"	TEXT,
	"Conf"	TEXT,
	"W"	REAL,
	"L"	REAL,
	"W/L%"	REAL,
	"MOV"	REAL,
	"ORtg"	REAL,
	"DRtg"	REAL,
	"NRtg"	REAL,
	PRIMARY KEY("id")
);

CREATE TABLE "PLAYER_TEAM" (
	"id_player"	INTEGER,
	"id_team"	INTEGER,
	"Player"	TEXT,
	"Team"	TEXT,
	"Rookie"	INTEGER,
	FOREIGN KEY("id_team") REFERENCES "TEAMS"("id"),
	PRIMARY KEY("id_player","id_team"),
	FOREIGN KEY("id_player") REFERENCES "PLAYERS"("id"),
	FOREIGN KEY("Rookie") REFERENCES "ROOKIES"("id")
);